# Generated by Django 2.2 on 2019-06-09 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('released', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to=music.models.media_directory_with_uuid)),
                ('genre', models.CharField(choices=[('afrobeat', 'AfroBeat'), ('hip hop', 'Hip Hop'), ('r&b', 'R&B'), ('pop', 'Pop'), ('gospel', 'Gospel'), ('soul', 'Soul'), ('n/a', 'N/A')], default='n/a', max_length=15)),
                ('is_favorite', models.BooleanField(default=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('released',),
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for your playlist', max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('duration', models.PositiveIntegerField()),
                ('audio_file', models.FileField(upload_to=music.models.media_directory_with_uuid)),
                ('released', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to=music.models.media_directory_with_uuid)),
                ('genre', models.CharField(choices=[('afrobeat', 'AfroBeat'), ('hip hop', 'Hip Hop'), ('r&b', 'R&B'), ('pop', 'Pop'), ('gospel', 'Gospel'), ('soul', 'Soul'), ('n/a', 'N/A')], default='n/a', max_length=15)),
                ('is_favorite', models.BooleanField(default=False)),
                ('lyrics', tinymce.models.HTMLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=music.models.media_directory_with_uuid)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ManyToManyField(blank=True, to='music.Playlist')),
            ],
            options={
                'ordering': ('title',),
                'abstract': False,
            },
        ),
    ]
